############################################################################
## 
## Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies). 
## All rights reserved. 
## Contact: Nokia Corporation (testabilitydriver@nokia.com) 
## 
## This file is part of TDriver. 
## 
## If you have questions regarding the use of this file, please contact 
## Nokia at testabilitydriver@nokia.com . 
## 
## This library is free software; you can redistribute it and/or 
## modify it under the terms of the GNU Lesser General Public 
## License version 2.1 as published by the Free Software Foundation 
## and appearing in the file LICENSE.LGPL included in the packaging 
## of this file. 
## 
############################################################################

module MobyController

  module Abstraction

    # TODO: document me
    def set_adapter( adapter )
  
      @sut_adapter = adapter
  
    end           

		# Execute the command(s). Sends output generated by make_message to the device using the @sut_adapter (see base class)     
		# == params
		# == returns
		# == raises
		def execute

			@sut_adapter.send_service_request( 
			
			  *make_message

      )

		end

  private
  
    # TODO: document me
    def make_message

      raise NotImplementedError, "controller not implemented for #{ self.class.name }"
    
    end
  
  end # Abstraction

end # MobyController
